# 로컬 백용

#  spring:
#    datasource:
#      url: jdbc:mysql://localhost:3306/port1
#      username: root
#      password: adminuser
#
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#
#server:
#  port: 8070


# 클라우드 배포 백용

spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: LTJMzwgeYbhkhDbgkbSLqaZvQPznoLaD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
