  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/port1
      username: root
      password: adminuser

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  server:
    port: 8070