spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: LTJMzwgeYbhkhDbgkbSLqaZvQPznoLaD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8070
